apiVersion: v1
kind: Service
metadata:
  name: griddy-pricing-prometheus-collector
spec:
  selector:
    app: griddy-pricing-prometheus-collector
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
