apiVersion: v1
kind: Service
metadata:
  name: griddy-pricing-prometheus-collector-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
spec:
  selector:
    app: griddy-pricing-prometheus-collector
  type: NodePort
  ports:
    - name: http-metrics
      port: 3000
      targetPort: 3000
      protocol: TCP

